---
- name: Create the EasyAppt database
  mysql_db: db={{ db_name }} state=present

- name: Create EasyAppt Database User
  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL

